[build]
  base = "."
  publish = "frontend"
  command = "echo 'No build command needed for static site'"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/api/*"
  to = "https://autotradex.onrender.com/api/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# This site should be deployed as autotradex.netlify.app
# Use this command to deploy:
# netlify deploy --dir=frontend --prod --site=autotradex
