services:
  - type: web
    name: autotradex
    env: python
    buildCommand: pip install -r requirements.txt && python fix_imports.py
    startCommand: python -m uvicorn backend.api.app:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
      - key: GROQ_API_KEY
        sync: false
      - key: QDRANT_URL
        sync: false
      - key: QDRANT_API_KEY
        sync: false
    plan: free
    instance_type: free
