services:
  - type: web
    name: gignova-backend
    env: python
    rootDir: GigNova
    buildCommand: cd backend && pip install -r requirements.txt
    startCommand: cd backend && uvicorn gignova.app:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PORT
        value: 10000
      - key: ENVIRONMENT
        value: production
      - key: JWT_SECRET
        generateValue: true
